/* automatically generated by rust-bindgen 0.72.1 */

pub const BONUS: u32 = 1;
extern "C" {
    pub fn ft_strlen(s: *const ::std::os::raw::c_char) -> usize;
}
extern "C" {
    pub fn ft_strcmp(
        s1: *const ::std::os::raw::c_char,
        s2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ft_strcpy(
        dst: *mut ::std::os::raw::c_char,
        src: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ft_strdup(s: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn ft_read(
        fd: ::std::os::raw::c_int,
        buf: *mut ::std::os::raw::c_void,
        nbytes: usize,
    ) -> isize;
}
extern "C" {
    pub fn ft_write(
        fd: ::std::os::raw::c_int,
        buf: *const ::std::os::raw::c_void,
        nbytes: usize,
    ) -> isize;
}
pub type t_list = s_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct s_list {
    pub data: *mut ::std::os::raw::c_void,
    pub next: *mut t_list,
}
pub type cmp = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type free_func = ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
extern "C" {
    pub fn ft_atoi_base(
        str_: *mut ::std::os::raw::c_char,
        base: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ft_list_push_front(begin_list: *mut *mut t_list, data: *mut ::std::os::raw::c_void);
}
extern "C" {
    pub fn ft_list_size(begin_list: *mut t_list) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn ft_list_sort(begin_list: *mut *mut t_list, cmp: cmp);
}
extern "C" {
    pub fn ft_list_remove_if(
        begin_list: *mut *mut t_list,
        data_ref: *mut ::std::os::raw::c_void,
        cmp: cmp,
        free_fct: free_func,
    );
}
